import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Dev Junkie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Web Dev Junkie</a>
        </h1>

        <div className={styles.grid}>
          <span>
            <h4>Signin to suggest a video topic </h4>
            <Link href="/">Signin</Link>
          </span>
        </div>
      </main>
    </div>
  );
};

export default Home;
