import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Dev Junkie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <span>
            <h4 className="my-4">Signin to suggest a video topic </h4>
            <Link href="/api/auth/signin">
              <a className="bg-blue-600 text-white py-2 px-4 rounded-md">
                Signin
              </a>
            </Link>
          </span>
        </div>
      </main>
    </div>
  );
};

export default Home;
