/* eslint-disable @next/next/no-img-element */
import { useSession, signIn, signOut } from "next-auth/react";
import { Modal } from "antd";
import "antd/dist/antd.css";
import type { NextPage } from "next";
import Head from "next/head";
import Ideas from "../components/ideas/ideas";
import { useState } from "react";
import CreateIdeaForm from "../components/ideas/create-idea";

const Home: NextPage = () => {
  const [visible, setVisible] = useState(false);
  const { data: session, status } = useSession();

  return (
    <div>
      <Head>
        <title>Web Dev Junkie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className="border-b-gray-300 border-b">
          <section className="flex justify-between items-center py-2">
            <span>
              <div>
                <img
                  src="https://yt3.ggpht.com/ytc/AKedOLQuaVb491-WzYU8eW8TeuUQfptbfeQXtPrHMtsq=s300-c-k-c0x00ffffff-no-rj"
                  alt=""
                  className="rounded-md w-12"
                />
              </div>
            </span>
            {status === "authenticated" ? (
              <div className="flex items-center gap-x-2">
                <span>
                  <h2 className="font-semibold text-xl">
                    {session?.user?.name}
                  </h2>
                </span>
                <button
                  onClick={() => setVisible(true)}
                  className="bg-blue-300 text-white rounded-md py-2 px-4"
                >
                  New idea
                </button>
                <button
                  onClick={() => signOut()}
                  className="text-blue-300 rounded-md py-2 px-4 border border-blue-300 hover:bg-blue-300"
                >
                  logout
                </button>
              </div>
            ) : (
              <>
                <button
                  onClick={() => signIn()}
                  className="bg-blue-400 text-white rounded-md py-2 px-4 flex gap-x-2 items-center"
                >
                  <span>Signin</span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"
                    />
                  </svg>
                </button>
              </>
            )}
          </section>
        </header>

        <section>
          <Ideas />
        </section>

        <section>
          <Modal
            title={
              <h3 className="text-xl font-semibold">Suggest A New Topic</h3>
            }
            visible={visible}
            centered
            onCancel={() => setVisible(false)}
            footer={null}
          >
            <CreateIdeaForm setVisible={() => setVisible(false)} />
          </Modal>
        </section>
      </main>
    </div>
  );
};

export default Home;
